version: "3.9"
services:
  api:    
    container_name: api
    build:
      context: .
      dockerfile: ./docker/Dockerfile      
    volumes:
      - .:/var/www/html
    ports:
      - "80:8080" 
  mysql:
    container_name: mysql
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: admin123
      MYSQL_DATABASE: maisaedu_db
    ports:
      - "3306:3306"
